### ISSUE TITLE
Nice but...

### ISSUE THREAD

**Issue by metal3d** [humantech/node-spamd#3]
Hi,

I just tried your module and it seems to be ok. There is a minor question that I need to ask.

In your test, you set "sender" to "you@yourdomain.com" and reciever to anotherdomain... is this not inverted ?

I mean... I will use your module to check blog comment as spam or not, the reciever should be "me" and sender to "who send comment"... My first try wad not really usefull:

```
var s = spamd('sender@gmail.com', 'myemail@gmail.com');

s.evaluate('Python-Quvi', '<a href=http://sacredmomentsproducts.com/#32175>buy xanax online</a> xanax effects diabetes - xanax dosage fear flying', function (res,m){console.log(res)})

 > { spam: false,
       evaluation: '2.4',
       allowed: '5.0',
       rules: 
       [ 'DKIM_ADSP_CUSTOM_MED',
          'DRUGS_ANXIETY',
          'FREEMAIL_ENVFROM_END_DIGIT',
          'FREEMAIL_FROM',
          'INVALID_DATE',
          'MIME_QP_LONG_LINE',
          'NML_ADSP_CUSTOM_MED',
          'NO_RECEIVED',
          'NO_RELAYS',
          'T_TO_NO_BRKTS_FREEMAIL' ] }
```

Ok... the message is not a full email... there is no headers etc... Maybe you can just point me what was not ok on my test :)

**Comment by ghophp** [comment]
Your code seems ok, the sender on our test says 'from@yourdomain.com', the 'from' means exactly what you said: 'who send the comment'. I guess that aren't issues here :)

**Comment by metal3d** [comment]
What I meant is that your "test" has inverted values:) , you've set "sender" to "yourmail@..." The "issue" is only in test code ;)

So now... I only have to check why the message that is spam is not reconnized as is.

PS: nice module

**Comment by ghophp** [comment]
i get it now, we see the module from a different perspective, we use spamd as a validator to our massive mail system, so, we are the sender. 

: )
